[package]
name = "nqc-executor"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
alloy = { workspace = true, features = ["sol-types"] }
nqc-aave-opportunity = { path = "../nqc-aave-opportunity" }
nqc-state = { path = "../nqc-state" }
thiserror.workspace = true

[lints]
workspace = true
